# Generated by Django 5.1.3 on 2025-03-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
